Vagrant.configure("2") do |config|
  ##############################################################
  # Wordpress VM 
  # Be sure to launch ./init.sh before vagrant provision 
  ##############################################################
  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = "wheezy64"
    wordpress.vm.box_url = "https://vagrant.irisa.fr/boxes/debian-wheezy-x64-puppet_3.0.1.box"

    #wordpress.vm.network :private_network, ip: "192.168.100.101"
    wordpress.vm.network "forwarded_port", guest: 80, host: 12345

    wordpress.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", "1"]   
    end

    wordpress.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "wordpress.pp"
      puppet.module_path = "puppet/modules"
    end
  end

end
