# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "irisa/ubuntu1410"
  config.vm.box_url = "https://vagrant.irisa.fr/boxes/irisa_ubuntu-14.10_puppet-3.6.1.box"
  config.vm.hostname = "mydocker"

  config.vm.network "forwarded_port", guest: 4243, host: 4243

  config.vm.provision "shell", path: "docker.sh"
end
